typedef enum {
   VTPARSE_STATE_ANYWHERE = 0,
   VTPARSE_STATE_CSI_ENTRY = 1,
   VTPARSE_STATE_CSI_IGNORE = 2,
   VTPARSE_STATE_CSI_INTERMEDIATE = 3,
   VTPARSE_STATE_CSI_PARAM = 4,
   VTPARSE_STATE_DCS_ENTRY = 5,
   VTPARSE_STATE_DCS_IGNORE = 6,
   VTPARSE_STATE_DCS_INTERMEDIATE = 7,
   VTPARSE_STATE_DCS_PARAM = 8,
   VTPARSE_STATE_DCS_PASSTHROUGH = 9,
   VTPARSE_STATE_ESCAPE = 10,
   VTPARSE_STATE_ESCAPE_INTERMEDIATE = 11,
   VTPARSE_STATE_GROUND = 12,
   VTPARSE_STATE_OSC_STRING = 13,
   VTPARSE_STATE_SOS_PM_APC_STRING = 14,
   VTPARSE_STATE_SS2_ENTRY = 15,
   VTPARSE_STATE_SS3_ENTRY = 16,
   VTPARSE_STATE_SS3_PARAM = 17,
} vtparse_state_t;

typedef enum {
   VTPARSE_ACTION_CLEAR = 1,
   VTPARSE_ACTION_COLLECT = 2,
   VTPARSE_ACTION_CSI_DISPATCH = 3,
   VTPARSE_ACTION_ESC_DISPATCH = 4,
   VTPARSE_ACTION_ESC_EXECUTE = 5,
   VTPARSE_ACTION_EXECUTE = 6,
   VTPARSE_ACTION_HOOK = 7,
   VTPARSE_ACTION_IGNORE = 8,
   VTPARSE_ACTION_OSC_END = 9,
   VTPARSE_ACTION_OSC_PUT = 10,
   VTPARSE_ACTION_OSC_START = 11,
   VTPARSE_ACTION_PARAM = 12,
   VTPARSE_ACTION_PRINT = 13,
   VTPARSE_ACTION_PUT = 14,
   VTPARSE_ACTION_SS2_DISPATCH = 15,
   VTPARSE_ACTION_SS3_DISPATCH = 16,
   VTPARSE_ACTION_UNHOOK = 17,
} vtparse_action_t;

typedef unsigned short state_change_t;
extern state_change_t STATE_TABLE[18][256];
extern vtparse_action_t ENTRY_ACTIONS[18];
extern vtparse_action_t EXIT_ACTIONS[18];
extern char *ACTION_NAMES[18];
extern char *STATE_NAMES[18];

